//! Data structs for queue jobs and experiments.

#[derive(Debug, Clone)]
pub struct QueueJob {
    pub id: i64,
    pub name: String,
    pub code: String,
    pub description: Option<String>,
    pub hypothesis: Option<String>,
    pub based_on: Option<String>,
    pub batch: Option<String>,
    pub priority: i64,
    pub strategy: String,
}

#[derive(Debug, Clone, Default)]
pub struct Experiment {
    pub name: String,
    pub backtest_id: String,
    pub batch: Option<String>,
    pub status: String,
    pub description: Option<String>,
    pub hypothesis: Option<String>,
    pub based_on: Option<String>,
    pub start_date: Option<String>,
    pub end_date: Option<String>,
    pub cagr: Option<f64>,
    pub dd: Option<f64>,
    pub car_mdd: Option<f64>,
    pub sharpe: Option<f64>,
    pub sortino: Option<f64>,
    pub total_orders: Option<i64>,
    pub win_rate: Option<f64>,
    pub alpha: Option<f64>,
    pub beta: Option<f64>,
    pub expectancy: Option<f64>,
    pub profit_loss_ratio: Option<f64>,
    pub annual_std_dev: Option<f64>,
    pub annual_variance: Option<f64>,
    pub information_ratio: Option<f64>,
    pub tracking_error: Option<f64>,
    pub treynor_ratio: Option<f64>,
    pub probabilistic_sharpe: Option<f64>,
    pub net_profit_pct: Option<f64>,
    pub loss_rate: Option<f64>,
    pub total_fees: Option<f64>,
    pub start_equity: Option<f64>,
    pub end_equity: Option<f64>,
    pub portfolio_turnover: Option<f64>,
    pub drawdown_recovery: Option<i64>,
    pub estimated_capacity: Option<f64>,
    pub lowest_capacity_asset: Option<String>,
    pub avg_win: Option<f64>,
    pub avg_loss: Option<f64>,
    pub backtest_run_start: Option<String>,
    pub backtest_run_end: Option<String>,
    pub code_hash: Option<String>,
    pub runtime_seconds: Option<f64>,
    pub project_id: Option<i64>,
}
